### ISSUE TITLE
run on web

### ISSUE THREAD

**Issue by goldbergmoshe** [saheeranas/react-native-wired-boilerplate#26]
Hi,

How ccan i run this on web?

**Comment by saheeranas** [comment]
Hi @goldbergmoshe ,

This starter supports Android and iOS only.

**Comment by goldbergmoshe** [comment]
thanks,
but on android am also getting the following error.
really want to try this boilerplate looks amazing, please can you assist

> RN_Wired_Boilerplate@0.0.1 android
> react-native run-android

info JS server already running.
* daemon not running; starting now at tcp:5037
* daemon started successfully
info Launching emulator...
error Failed to launch emulator. Reason: It took too long to start and connect with Android emulator: Pixel_3a_API_33_x86_64. You can try starting the emulator manually from the terminal with: C:\Users\tanze\AppData\Local\Android\Sdk/emulator/emulator @Pixel_3a_API_33_x86_64.
warn Please launch an emulator manually or connect a device. Otherwise app may fail to launch.
info Installing the app...

FAILURE: Build failed with an exception.

* Where:
Script 'C:\Users\tanze\Downloads\react-native-wired-boilerplate\node_modules\@react-native-community\cli-platform-android\native_modules.gradle' line: 450

* What went wrong:
A problem occurred evaluating script.
> Calling `[node, C:\Users\tanze\Downloads\react-native-wired-boilerplate\node_modules\@react-native-community\cli\build\bin.js, config]` finished with an exception. Error message: groovy.json.JsonException: Unable to determine the current character, it is not a string, number, array, or object

  The current character read is 'i' with an int value of 105
  Unable to determine the current character, it is not a string, number, array, or object
  line number 1
  index number 0
  info Run CLI with --verbose flag for more details.
  ^. Output: info Run CLI with --verbose flag for more details.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* Where:
Script 'C:\Users\tanze\Downloads\react-native-wired-boilerplate\node_modules\@react-native-community\cli-platform-android\native_modules.gradle' line: 450

* What went wrong:
A problem occurred evaluating script.
> Calling `[node, C:\Users\tanze\Downloads\react-native-wired-boilerplate\node_modules\@react-native-community\cli\build\bin.js, config]` finished with an exception. Error message: groovy.json.JsonException: Unable to determine the current character, it is not a string, number, array, or object

  The current character read is 'i' with an int value of 105
  Unable to determine the current character, it is not a string, number, array, or object
  line number 1
  index number 0
  info Run CLI with --verbose flag for more details.
  ^. Output: info Run CLI with --verbose flag for more details.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s

    at makeError (C:\Users\tanze\Downloads\react-native-wired-boilerplate\node_modules\@react-native-community\cli-platform-android\node_modules\execa\index.js:174:9)
    at C:\Users\tanze\Downloads\react-native-wired-boilerplate\node_modules\@react-native-community\cli-platform-android\node_modules\execa\index.js:278:16
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runOnAllDevices (C:\Users\tanze\Downloads\react-native-wired-boilerplate\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:82:7)
    at async Command.handleAction (C:\Users\tanze\Downloads\react-native-wired-boilerplate\node_modules\@react-native-community\cli\build\index.js:108:9)
info Run CLI with --verbose flag for more details.
PS C:\Users\tanze\Downloads\react-native-wired-boilerplate>

it is win11

**Comment by saheeranas** [comment]
The repo is basically a starter template. Try creating a bare react native app by running `npx react-native init YourAppName` and make sure the development environment is set up correct

**Comment by goldbergmoshe** [comment]
that works, just this for some reason is giving me an error in the community cli build.

**Comment by goldbergmoshe** [comment]
can you try cloning it and running with android? For some reason am getting the above error. Have other projects that work fine, not sure what it is iwht this and would love to check this out. thanks!
